<?php
require_once('Models/Upload.php');
include('Email/Email.php');
//Déclaration des constantes
$emailNoSend      = false;
$emptyDest        = "Recipient Email";
$emptyExp         = "Sender email";
$displayDivError  = '';
$displayDivErrorSender='';
$displayDivErrorExp='';
$displayDivErrorV='';
$divResponseError = '<div class="rouge">';
$divResponseValid = '<div class="vert">';
$closeDiv         = '</div>';
$sujetGen         = "The sender did not leave a message";
$messageGen       = "This file was generated by YouZip.";


error_reporting(E_ERROR | E_PARSE);

if (isset($_POST['uploadform']) && !empty($_POST)) {
    
    //check email expéditeur
    if (!empty($_POST['mail_exp'])) {
        if (filter_var($_POST['mail_exp'], FILTER_VALIDATE_EMAIL)) {
            $tabValue['mail_exp'] = $_POST['mail_exp'];
            $mail_exp = $_POST['mail_exp'];
        } else {
            $emptyExp = 'Email Expéditeur non valide';
        }
    } else {
        $displayDivErrorSender .= $divResponseError . 'The Sender address is empty' . $closeDiv;
    }

    //check email destinataire
    if (!empty($_POST['mail_dest'])) {
        if (filter_var($_POST['mail_dest'], FILTER_VALIDATE_EMAIL)) {
            $tabValue['mail_dest'] = $_POST['mail_dest'];
            $mail_dest = $_POST['mail_dest'];
        } else {
            $emptyDest = 'Invalid recipient email';
        }
    } else {
        $displayDivErrorExp .= $divResponseError . 'The Recipient address is empty.' . $closeDiv;
    }

    // Testons si le fichier a bien été chargé et s'il n'y a pas d'erreur au chargement du fichier
    if (!empty($_FILES['zip']['name'][0])) {

        
        
                $nameTmp = time();
                $imageCount = count($_FILES['zip']['name']);
                //on instancie un nouveau zip
                $zip = new ZipArchive;
                $zip_name="Upload/" . $nameTmp . ".zip";
                $zip->open($zip_name, ZipArchive::CREATE) ;
                   
              
                  $imageCount = count($_FILES['zip']['name']);
                  for ($i = 0; $i < $imageCount; $i++) {
              if ($_FILES['zip']['size'][$i] <= 2000000) {
                   
                   
                    $zip->addFromString($_FILES['zip']['name'][$i], file_get_contents($_FILES['zip']['tmp_name'][$i]));
              }else{
                    $displayDivErrorV .= $divResponseError . 'check the size' . $closeDiv;
                }
                    
                  }
               $zip->close();
                
    
                }else{
                    $displayDivErrorV .= $divResponseError . 'no files found' . $closeDiv;
                }
        $tabValue['zip'] = $zip_name;
    
     if (empty($_POST['sujet'])) {
        $tabValue['sujet'] = $sujetGen;
     } 
     else 
     {
        $tabValue['sujet'] = $_POST['sujet'];
        $subject = $_POST['sujet'];
     }
    
    if (empty($_POST['message'])) {
        $tabValue['message'] = $messageGen;
    }
    else 
    {
        $tabValue['message'] = $_POST['message'];
        $message = $_POST['message'];
    }
    
    $result = insertUpload($tabValue, $pdo);
  
   
    
        $upload = 'http://localhost/www/YouZip/index.php?page=download&link=' . $nameTmp . '.zip';
    
  
    $mailbody = mailCreate($upload, $mail_exp, $tabValue['sujet'], $tabValue['message']);


    if ($_SERVER['SERVER_NAME'] === "localhost" && ($result === true && $emailNoSend === false)) {
        
        require_once('vendor/autoload.php');
        
        $transport = (new Swift_SmtpTransport('smtp.mailtrap.io', 465)) 
            ->setUsername('301c78b5e44085')
            ->setPassword('daa910e783f743');
      
        $mailer = new Swift_Mailer($transport);
        $date = date('j, F Y h:i A');
       
        $message = (new Swift_Message($sujetGen))
            ->setFrom([$mail_dest => 'Yes Transfert'])
            ->setTo([$mail_exp])
            ->setBody($mailbody);
        
        $type = $message->getHeaders()->get('Content-Type');
        $type->setValue('text/html');
        $type->setParameter('charset', 'utf-8');
        
        $resultMail = $mailer->send($message);
        if ($resultMail === 1) {
            $displayDivError .= $divResponseValid . 'Your email has been sent' . $closeDiv;
        } else {
            $displayDivError .= $divResponseError . 'Error while sending Email' . $closeDiv;
        }
    } else {
        $displayDivError .= $divResponseError . 'Your Email could not be sent' . $closeDiv;
    }
}

require_once('Views/homeView.php');
